matrix:
  include:
# DOCKER && LINUX
    - os: linux
      language: go
      go: 1.10.x
      dist: trusty
      sudo: required
      services:
            - docker
            - mongodb
      env:
          - GIT_BRANCH=$TRAVIS_BRANCH
          - TARGET_OS=linux
          - DB=127.0.0.1:27017
          - CRYPTO_CND_URL=virgil-crypto-2.4.4-go-linux-x86_64.tgz 
          - CC=gcc-8 
          - CXX=g++-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
# MACOS
    - os: osx
      language: go
      go: 1.10.x
      services:
          - mongodb
      env:
          - TARGET_OS=darwin
          - DB=127.0.0.1:27017
          - CRYPTO_CND_URL=virgil-crypto-2.4.4-go-darwin-17.5-x86_64.tgz

before_install:  
  - if [[ "$TARGET_OS" == "darwin" ]]; then
      brew update;
      brew install swig mongodb;
      brew tap homebrew/services;
      brew services start mongodb;
    fi
  - 'if [ "$TARGET_OS" = "linux" ]; then
      echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc;
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" virgilsecurity-docker-core.bintray.io;
      docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD";
      gcc --version;
      g++ --version;
    fi'
  - go get -d gopkg.in/virgilsecurity/virgil-crypto-go.v5;
  - wget https://cdn.virgilsecurity.com/virgil-crypto/go/$CRYPTO_CND_URL ;
  - tar -xvf $CRYPTO_CND_URL  --strip-components=1 -C $GOPATH/src/gopkg.in/virgilsecurity/virgil-crypto-go.v5/;
  - rm $CRYPTO_CND_URL;

install:
  - make get

script:
  - make
  - make test-all
  - 'if [ "$TARGET_OS" = "linux" ]; then
      make docker-build;
    fi'
  - make build-artifacts

after_seccess:
  - 'if [ "$TARGET_OS" = "linux" ]; then
      make docker-inspect;
    fi'

deploy:
  - provider: releases
    api_key:
      secure: niW59QpncwYufI1zOMNNEWWC2XqNJJ3vpD/3Ye2Z3Rb7vpYTz4t0qDpa900tdhTnFMUNxpwvs4JMBwGxJ5qhq+e5ceC+3ZWNexshs6SNHB+tmMIWkGt3QSPBjqQKMTcsLr7TAPGdVehAJ36g4WNBAsExlXWz0AcgPnpAulTXQ/vn6D3/PziAPkgFoI2wa5Kyhv1tdmGcGKHLZRKs58YMp0XftsZBo4HAkvuJJknFJtRkbLcACSJHqa2Jq+wqZZhon+wxfJJUYiDMsJ806plNUhe/VhLH3/tvuzQvijRl2Hjl7+W7EM3sTuheTVycWQTEmAD2TapMh18DBG6JxIiIsxT5Ndsg/ksVpPvYRF0n1uhszY7ZQqTKoMIpwQm7a3omTXEqBFtEAdtwhmGWyCi4uZBTeC+MJLYh5alHWlOSpO23q2mrDWVixWN//VYZUVZoi99wblNkOOexHCsj3mSxfJ2qJP+3tcmEd5TR6iI7glqeV4mvljTq+yVtD3s0gbT/uz9BV+mcR+xDGffjplAR6mZPhujniB7OvyVLP2a5rUFV4X8e0gDrPOI18hHl7F9aRQnIjDcn1edllPifP31HXQ2tDiXDCmNPRW0QfPLLCPmu1aJHJkRTvjFQ+V+R41KpUufouHrIbsmYsuS4XpG4e0rha+SebfB2/sBTAbRYPVs=
    skip_cleanup: true
    file_glob: true
    file: artf/*
    on:
      tags: true
      repo: VirgilSecurity/virgil-services-auth
# Update latest docker image
  - provider: script
    script: make docker-publish
    on:
      branch: master
      condition: "$TARGET_OS = linux"
# Publish tagged docker image
  - provider: script
    script: make docker-publish
    on:
      tags: true
      condition: "$TARGET_OS = linux"
